### ISSUE TITLE
Nombres de clases que sean CLAROS

### ISSUE THREAD

**Issue by nmicht** [HawkRS/Terrasse#19]
Ejemplo, si la clase es solo para poner un color, no sería mejor que la clase hiciera referencia a algo como:

``` css
.color_rojo{
   color: ###
}
```
